name: ivissearch
channels:
  - damianavila82
  - satra
  - pluraldatum
  - glemaitre
  - conda-forge
  - defaults
  - simpleitk
dependencies:
  - numpy
  - scipy
  - matplotlib
  - pandas
  - bokeh
  - SimpleITK
  - scikit-image<=0.20
  - scikit-learn<=0.20
  - nbserverproxy
  - appmode
  - tensorflow
  - pip:
    - keras
    - plotly
    - bs4
    - seaborn==0.7.1
    - cloudpickle
    - fileupload
    - ipywidgets>=7.4.0
    - ipywebrtc
    - git+https://github.com/chestrays/cornerstone_widget
